"""Add reminder_time column

Revision ID: 0b7ccaea841e
Revises: 39e1b9558a1b
Create Date: 2023-10-16 07:40:37.886483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7ccaea841e'
down_revision = '39e1b9558a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the reminder_time column
    op.drop_column('task', 'scheduled_time')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###
